language: python

python:
  - 3.7
  - 3.8

install:
  - make virtualenv

script:
  - make test

cache: pip

jobs:
  fast_finish: true

branches:
  only:
  - master

after_success:
  - build/virtualenv/bin/python/codecov
