language: python

python:
  - "3.7"

before_install:
  - echo -e "\n\nmachine github.com\n  $CI_TOKEN\n" >~/.netrc
  - git submodule update --init --recursive

install:
  - make virtualenv

script:
  - make test
